### PR TITLE
Merge v5.10.58

### PR DESCRIPTION
**Pull request by ghost**
Merged cleanly.
Includes update to changelog for our packaging.

Jira: NAS-111882

### CODE REVIEW

**Comment by anodos325** [comment]
Did we do a testbuild?

**Comment by ghost** [comment]
I'm about to do that as I'm reminded we don't have CI yet.

**Comment by rick-mesta** [comment]
@freqlabs: how much vetting do we typically do when we do a Linux refresh like this ? i.e. simple Build or do we actually generate SCALE bits with the incoming kernel and make sure it's tested ? (for my education only)

**Comment by ghost** [comment]
@rick-mesta It would be nice to have a job in Jenkins like we have for scale-build that builds everything and runs through our internal tests. The updates to the Linux kernel should be infrequent enough for that to be practical. We could also probably get a basic build test done in a github CI runner, and I created NAS-111045 to request this, but it ended up assigned to me and I've not become familiar enough with github's CI to implement it yet. :sweat_smile:

**Comment by ghost** [comment]
The build was successful. I did a full build of SCALE.

**Review by rick-mesta — APPROVED** [review]

**Pull request merged**
