### PR TITLE
NAS-132233 / 24.10.1 / Cherry-pick NFS-related fixes

### PR DESCRIPTION
**Pull request by anodos325**
- nfsd: fix delegation_blocked() to block correctly for at least 30 seconds
- nfsd: return -EINVAL when namelen is 0
- nfsd: fix refcount leak when file is unhashed after being found
- SUNRPC: Fix a race to wake a sync task
- NFSv4: Add missing rescheduling points in nfs_client_return_marked_delegations
- nfs: fix memory leak in error path of nfs4_do_reclaim
- SUNRPC: Fix integer overflow in decode_rc_list()
- NFSv4: Prevent NULL-pointer dereference in nfs42_complete_copies()
- NFS: Avoid unnecessary rescanning of the per-server delegation list
- NFSD: Fix NFSv4's PUTPUBFH operation

### CODE REVIEW

**Comment by yocalebo** [comment]
@usaleem-ix We're cherry-picking NFS related fixes into 24.10.1 because rebasing our current linux repo on upstream brings in ~32k lines of change and some of the subsystems that are being touched have a direct impact on our HA product (i.e. CMA).

**Comment by amotin** [comment]
> We're cherry-picking NFS related fixes into 24.10.1 because rebasing our current linux repo on upstream brings in ~32k lines of change and some of the subsystems that are being touched have a direct impact on our HA product (i.e. CMA).

Just for note, some of regressions we saw lately were specifically triggered by cherry-pick of some changes by somebody, that were depending on some other changes that were not included.

**Review by bmeagherix — APPROVED** [review]
LGTM, although also note that fully 5/10 of these commits are client-side.

**Comment by anodos325** [comment]
Solutions team is using NFS client for some designed workflows so we need to fix client bugs as well unfortunately.

**Review by mgrimesix — APPROVED** [review]
LGTM

**Review by umsaleem — APPROVED** [review]
@yocalebo We usually do a merge of upstream release instead of rebase, we get quite less number of conflicts that way.

This looks good to me, but if we are open to merge v6.6.59 for EE, I can do that.

**Pull request merged**
