### PR TITLE
NAS-116821 / None / ses: AHCI enclosure may be added after elements

### PR DESCRIPTION
**Pull request by ghost**
Don't assume the enclosure was already registered when adding elements.

### CODE REVIEW

**Review by rick-mesta — APPROVED** [review]

**Comment by william-gr** [comment]
Does this cause a full kernel panic or only the enclosure module is "halted"?

**Comment by ghost** [comment]
@william-gr judging from the ticket this crashed the `ses` module and hung `systemd-udevd` at boot.

**Comment by william-gr** [comment]
@freqlabs what is the trigger for this? It will depend on the probe order of the hardware? Trying to gauge % of affected users in the field for a hotfix release

**Comment by ghost** [comment]
Yes it is a result of the probe order. I do not know how likely an occurrence this is, but in the ticket is mentioned the Dell PowerEdge R740xd2. It may not be specific to the hardware though. It could be a result of udev parallelizing the probe and the AHCI enclosure probe taking longer than a disk probe for any reason. That's just a theory.

**Comment by larod241** [comment]
The problem is présent on a HPE Gen10 plus too.

**Pull request merged**
